### ISSUE TITLE
Device Handshake and Identification

### ISSUE THREAD

**Issue by SeBassTian23** [Photosynq/PhotosynQ-Firmware#1]
Can we set up an example on how to do the handshake (autenticate the device) and get the information about the device. This should be the final and no backwards compatibility is needed from the apps perspective. What needs to be send and what is the exact response? It would be important, so we can identify the device without doubt and we can asure, that for example the correct firmware is flashed, when the device is connected. One assumption is all data send from the device to the app is a valid JSON object and has a crc32 checksum. Will the same be true for data send to the device? I would like to keep the handshake simple...

**Comment by gbathree** [comment]
Let's sit and define on Monday, but I think that's already been determined
- handshare is "XXXXX ready" , and device info produces outputs:
device_name, device_version, device_id, firmware_version .  All outputs
from device, with exception of XXXX ready, are valid JSON with CRC check.
The only other thing I can think is we could also provide battery status as
part of device info.  That would be simply "battery":<1-5>.



On Sat, Apr 16, 2016 at 9:09 AM, Sebastian <notifications@github.com> wrote:

> Assigned #1 <https://github.com/Photosynq/PhotosynQ-Firmware/issues/1> to
> @gbathree <https://github.com/gbathree>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Photosynq/PhotosynQ-Firmware/issues/1#event-629912096>
>



-- 
Greg Austic

2198 Seminole Dr.
Okemos, MI 48864
(919) 545 1083

Work -www.photosynq.org
