### ISSUE TITLE
Missing pulses cause the JSON parser to fail

### ISSUE THREAD

**Issue by SeBassTian23** [Photosynq/PhotosynQ-Firmware#5]
When no pulses, only environmentals are defined, in a protocol, there is an additional `]}` at the end of the instrument output, causing the javascript JSON parser to fail.

**Comment by gbathree** [comment]
Attempted to replicate but couldn't, please provide a use case to test.  Tried [{"environmental":[["light_intensity"]]}], and [{}] but both produced the correct outputs.
